---
- name: PHP | CHECK REMI REPO
  yum:
    name: remi-release
    state: present
  register: find_remi
  ignore_errors: true

- name: PHP | INSTALL REMI
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present
  when: find_remi|failed

- name: PHP | INSTALL DEFAULT MODULES
  yum:
    name: {{ item }}
    state: present
    enablerepo: remi,remi-php{{ php_version }}
  with_items:
    - php-cli
    - php-process
    - php-imap
    - php-xml
    - php-common
    - php-fpm
    - php-pdo
    - php-mysqlnd
    - php-mcrypt
    - php-mbstring
    - php-bcmath
    - php-mbstring
    - php-intl
    - php-gd
    - php-pecl-jsonc
    - php-opcache
  notify: restart php-fpm

- name: PHP | INSTALL ADDITIONAL MODULES
  yum:
    name: {{ item }}
    state: present
    enablerepo: remi,remi-php{{ php_version }}
  with_items: "{{ modules }}"

- name: PHP | RUN FPM ON STARTUP
  service: name=php-fpm enabled=yes state=started

- name: PHP | SET FPM USER
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "{{ item.key }}"
    line: "{{ item.value }}"
  notify: restart php-fpm
  with_dict: "{{ fpm_config }}"

- name: PHP | SET OWNERSHIP
  file:
    path: /var/lib/php/session
    owner: "{{ user }}"
    group: "{{ group }}"
    state: directory
  notify: restart php-fpm

- name: PHP | SET PHP INI PARAMS
  lineinfile:
    dest: "/etc/php.ini"
    regexp: "^;?{{ item.key }} *=.*$"
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ params }}"
  notify: reload php-fpm