---
- name: NGINX | ADD USERS
  user:
    name: "{{ user }}"

- name: NGINX | INCLUDE CENTOS
  include_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

- name: NGINX | INCLUDE CENTOS
  include_tasks: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
